<?php

namespace App\Controller\Custom;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;

class MainController extends AbstractController
{
    protected function isAdminAuthenticated()
    {
        $session = $this->get('session');

        return $session->has('hr_id');
    }

    protected function json($data, int $status = 200, array $headers = [], array $context = []): JsonResponse
    {
        $headers += [
            'Access-Control-Allow-origin' => '*',
            'Access-Control-Allow-Credentials' => 'true',
            'Access-Control-Allow-Headers' => 'Origin, Content-Type, Accept, X-Auth-Token',
            'Access-Control-Expose-Headers' => 'Content-Length, X-Kuma-Revision',
            'Access-Control-Allow-Methods' => 'GET, POST, PUT, DELETE, PATCH, OPTIONS',
        ];
        return parent::json($data, $status, $headers, $context); // TODO: Change the autogenerated stub
    }
}
